### ISSUE TITLE
Images are not correctly sized or centered

### ISSUE THREAD

**Issue by beta382** [BenAndCarl/Faces#1]
The title makes it seem worse than it really is, you're really just just off by a point. I gathered the following numbers from Cycript in Safe Mode, so I'm sure that there isn't anything else I have installed that may be shifting views around or resizing them. Note that I don't have an iPad, so I don't know about correctness on that end.

Image for reference:
![](http://i.imgur.com/q9voGyM.jpg)

(Notice how there is less ring below than there is above. Also you can slightly see how on the sides, some of the ring shows through the image due to overlap)

The encapsulating `TPRevealingRingView` has a frame `(0 0; 95 88)`, the innermost (not depth, but visually) `TPPathView` has a frame `(11.5 8; 72 72)` (which, if you do the math, is perfectly centered in the TPRevealingRingView with even padding). 

You have:

``` objective-c
if (IS_NOT_IPAD) {
    imageView.frame = CGRectMake(0, 0, 73, 73);
    imageView.center = CGPointMake(47.5, 44.5);
}
```

If your intent is to have the image fit perfectly inside the ring, it should be:

``` objective-c
if (IS_NOT_IPAD) {
    imageView.frame = CGRectMake(0, 0, 72, 72); // Width and height of the innermost TPPathView
    imageView.center = CGPointMake(47.5, 44); // Half the w/h of the TPRevealingRingView, which will properly center the image
}
```

You could probably alternatively use:

``` objective-c
if (IS_NOT_IPAD) {
    imageView.frame = CGRectMake(11.5, 8, 72, 72);
}
```

although I've never really touched Objective-C in my life, and don't really know if the latter is proper view creation.

You might could even grab the frame directly from the innermost TPPathView, and this would probably eliminate the need for awkward `IS_NOT_IPAD` special code, and make Faces more robust with screen sizes in general.

**Comment by CPDigitalDarkroom** [comment]
You're right, it is slightly off center. I hadn't noticed it yet and will be fixing while updating and adding features in the next update.

**Comment by beta382** [comment]
I consider this issue resolved (just make sure iPad is correctly centered, cycript view inspection is awesome).
